### ISSUE TITLE
La formación de los profesores y las horas institucionales.

### ISSUE THREAD

**Issue by Danieldaza** [ESTUNSAM/arenadejuego#2]
pensar de nuevo la agenda universal de temas. Cómo pensar lo situado de esa agenda. Las horas institucionales más allá de la planificación, aportando mayor presencia en el proyecto, en la  formación, las reuniones de equipo o en el barrio. 
- Nuevas capacidades docentes para nuevos alumnos. Los problemas que traen las tecnologías digitales y las soluciones que nos obligan a inventar.  
- Autoridad, respeto y confianza como capacidades docentes necesarias.

**Comment by alvarmaciel** [comment]
che creo que falta un punto

**Comment by Danieldaza** [comment]
YA LO AGREGUE

**Comment by alvarmaciel** [comment]
lito capuitulo cerrado
